### ISSUE TITLE
UAT Case 2 - Logged in user requests access to one or more restricted files in single dataset

### ISSUE THREAD

**Issue by mdmADA** [ADA-ANU/Request-Access-Console#40]
Pre-condition: UAT Case 1 has been executed prior to this test case
This test case continues from end of UAT Case 1

Steps:
1. [request access tool] The user enters the guestbook field values including all required fields.
2. [request access tool] The user clicks Submit
   
Expected results:
1. A popup with the files the user requested access to is presented to the user (OK is the only choice to close the popup)
2. A ticket is created in osticket - 1 dataset request results in 1 osticket
       - the ticket contains system (database info about the user and the request) 
       and
       - user-specified details (files requested and guestbook responses)
3. The user receives an email from ada@anu.edu.au
              - the email contains the responses the user entered in the form at the point in time when the user clicked 'Submit'
              - the email also contains the Ticket number of the ticket
4. when the user goes back to the Dataverse page from step 1 and refreshes that page, the drop-down for all the files they requested in the remaining steps shows 'Access Requested' and is disabled (not clickable).

**Comment by HaddicanGitHub** [comment]
User Acceptance Testing continued from Test Case 1. 
1. Online Guestbook answers entered
2. Clicked 'Submit'
3. Presented with 'T&Cs' again, accepted both. 
4. Selected 'Request Access'
5. Pop up with 'OK' option appears, and 'OK' selected. 
6. Form cannot be edited on original page and now states 'This form has been submitted.'
7. There is a Ticket in OSTicket for the access request with user and use information (but no email to ADA inbox notifying me of the OSTicket - I had to navigate to OSTicket to find this)
MM: Issue #71 - osticket email alert to all osticket staff now occurs when a new ticket is created (no ticket to ada@anu.edu.au as that would result in a second ticket for the same request).

8. User Email received with OSTicket Number, Requested File info, Guestbook Responses, and Terms of Access. 
9. Navigated back to Dataverse Page for Dataset and all files access requested to show 'Access Requested', no option to request access.

**Comment by HeatherLeasor** [comment]
sorry i don't see the difference between use case one
