### ISSUE TITLE
UAT Case 3 - Logged in user Saves access request details to one or more restricted files in single dataset

### ISSUE THREAD

**Issue by mdmADA** [ADA-ANU/Request-Access-Console#41]
Pre-condition: UAT Case 1 has been successfully executed
This test case continues from the end of UAT Case 1 

Steps:
1. [requestaccess tool] The user enters the form details.
2. [requestaccess tool] The user clicks 'Save'.

Expected Results:
1. A popup is presented to the user saying their responses have been saved (with a list of the files requested)

2. Additional step: User checks the checkbox beside 'Receive email notification regarding saved request.'  and then hits 'Save' button

Expected Result:
1. The user receives an email that contains their responses and for which dataset they were requesting at the point in time when they clicked 'Save'
   The email indicates it is only saved responses and that the user will need to return to the request access to complete their submission.

**Comment by HaddicanGitHub** [comment]
Continued from Use Case 1
1. Online Guestbook responses entered
2. Clicked 'Save'
3. Pop-up presented confirming responses saved. 
4. Selected checkbox to receive email and selected 'Save'. 
5. Email received to user account with dataset details and access guestbook responses.
6. Email also contains link to re-access the saved request. 
7. When selected, takes me to the saved data and able to then follow the steps from Use Case 2 to request access.

**Comment by HaddicanGitHub** [comment]
We could perhaps make it clearer, i.e. bold up-front message in the email that says something along the lines of 'Your Access Request to.... has been saved. You still need to submit this request'.

The email content received is as follows:

Dear Dave,

Your responses for accessing dataset "ANU Poll 47 (August 2021): Mental health and schooling of children during COVID 19 (doi:10.26193/YB3CXX)" have been saved. Please find the following URL to continue editing the responses.

**Comment by HeatherLeasor** [comment]
when you reject someone as a owner you have to hit refresh to see if the reject took

MM: that's a Dataverse bug.

**Comment by HeatherLeasor** [comment]
1 request access
2 hit save 
**3 email received email does not say about the additional siblings that requested.**
4 hit the save button again get the email confirmation pop up again
5 hit submit again  got opps
no indication in the gray out that means already requested (can we get something to indicate that it is already requested)

UAT Case 3 is about requesting files in a single dataset - does not include siblings
