### ISSUE TITLE
UAT Case 4 - User uses the re-open form link appended to the ticket created for their access request

### ISSUE THREAD

**Issue by mdmADA** [ADA-ANU/Request-Access-Console#47]
Pre-requisites: 
- a Dataverse user has requested access to one or more datasets through the request access tool
- a ticket for the request was created in osticket and with a 'form re-open' url (text) appended to the ticket

Steps.
1. The ADA access manager handling the ticket emails the text url to the user specifying the problems in their request access submission and instructs the user to copy and paste the url into a browser address bar to edit their application
2. the user receives the email with the instructions and the text url
3.  the user copies the form re-open text url in the email received from ADA and pastes it into a browser address bar and hits enter

Expected result:
1. the requestaccess tool opens in a new tab of the user's default web browser
2. the guestbook form is displayed to the user with the fields populated by their previous responses
3. the request access has been reset 
    - the records from the 'fileaccessrequests' table for the user and the reset datafiles have been cleared (confirmation by admin user required)
    - in Dataverse, for the requester, the 'Access Requested' that would have appeared in the file's drop down button after the user first requested access is now 'Request Access' (may have to refresh Dataverse dataset page) 
    - in Dataverse, for the ADA access/admin team, the user is deleted from the 'Requests' area of the File Permissions for the dataset

**Comment by HaddicanGitHub** [comment]
Ticket - #701708 created: https://support.ada.edu.au/scp/tickets.php?id=29272 from access request. Ticket contains re-open link for ADA User Services Staff to use. 

1. Link copied from ticket and sent to the user using 'Copy Link'. CC'd ADA into email to create new OSTicket #506601: https://support.ada.edu.au/scp/tickets.php?id=29280
2. Received email to test account (and also in OSTicket)
3. Made sure all user windows in DV5 were closed.
4. When I select link, following message is received 'This link has been used, please contact ADA access team for help.' Cannot go beyond this step. 

Link does not open from original ticket, user email, or ADA email. Unable to re-open application to request access.

**Comment by HaddicanGitHub** [comment]
If the original OSTicket created by the applicant when raising the access request is responded to, the user will be sent the re-open link in the message trail. Activating the link in this message works (unlike copying the link and emailing it to the user).

I have also discovered that using the Ctrl+C and Ctrl+P options to copy and paste the re-open link into an email to the user works, however, if you attempt to highlight and then copy using the right click feature or indeed paste into the original email using the right click features, this appears to activate the link and the user is then presented with the message that the link has already been used.

**Comment by HaddicanGitHub** [comment]
When the link has successfully sent to the user (i.e. Ctrl+C and Ctrl+P), and the link is clicked on by the user:
1. The Request Access information is removed from the DV Request Access Users/Groups Table and the User sees the Request Access option in DV where it used to say Access Requested.
2. The Request Access window opens for the user
3. The Guestbook is displaying the original responses
4. Upon updating the responses, when the user selects 'Submit'
5. The 'T&Cs' window is displayed with the tick box options
6. Selecting the 'Terms of Access and Use' boxes, followed by 'Request Access' opens the 'Requests Submitted' window with the 'OK' option
7. Selected 'OK' and closed the request window. The Request re-appears in the DV Request Access Users/Groups Table and the User sees the Access Requested option in DV again, where it previously said Request Access
8. A new OSTicket is raised

**Comment by mdmADA** [comment]
This UAC Case works as expected.
