### ISSUE TITLE
UAT Case 5 - User edits and re-submits an access request

### ISSUE THREAD

**Issue by mdmADA** [ADA-ANU/Request-Access-Console#48]
Pre-requisite: UAT Case 4 has been successfully completed
This use case continues from the end of UAT Case 4

Steps:
1. User edits the request access application previously submitted (hopefully as instructed by the request access team)
2. User clicks 'Submit'

Expected Results:
1. The new request access details are written in the database so that the requester's name appears in the 'Requests' section of the Dataverse UI for edit->permissions->file
2. A new ticket is created in osticket with:
    - the new request access details
    - the previous ticket #  **(issue #60 is created for this)**
    - a new re-open form link
3. an email is sent to the requester with the request access details
4. when the requester goes back to Dataverse and refreshes the dataset page, the Drop-down button links for each restricted file in the access request indicates 'Access Requested'

**Comment by HaddicanGitHub** [comment]
Unable to perform as unable to re-open access request at UAT Case 4

**Comment by HeatherLeasor** [comment]
issue is when respondig out of ozticket and user then clicks link and starts new ticket. or when i awrded them in and respond in osticket theysee full chain and if click on wrong the user can now see manage permissions

**Comment by HeatherLeasor** [comment]
in current ozticket the user doesn't see what is above the line  on ozticket

**Comment by HaddicanGitHub** [comment]
When the link has successfully sent to the user (i.e. Ctrl+C and Ctrl+P) at UAT Case 4, and the link is clicked on by the user opening the Request Access window:

1. The Guestbook is displaying the original responses
2. Upon updating the responses, when the user selects 'Submit'
3. The 'T&Cs' window is displayed with the tick box options
4. Selecting the 'Terms of Access and Use' boxes, followed by 'Request Access' opens the 'Requests Submitted' window with the 'OK' option
5. Selected 'OK' and closed the request window. 
6. The Request re-appears in the DV Request Access Users/Groups Table to User Services and the User sees the Access Requested option in DV again, where it previously said Request Access
7. A new OSTicket is raised with new ticket details, a new re-set link - I cannot see the original OSTicket Number
8. Email is received by User with application details

**Comment by HeatherLeasor** [comment]
MJ to add previous reopened osticket number so that we can easily link (Issue #60 )
