### ISSUE TITLE
logging out

### ISSUE THREAD

**Issue by HeatherLeasor** [ADA-ANU/Request-Access-Console#55]
i was logged in as my test account i went to log out and got error 500 Internal Server Error

**Comment by mdmADA** [comment]
Had you left your browser open after logging in and for more than a day?

**Comment by mdmADA** [comment]
The session times out if you leave your browser open for more than 24 hours (I think) after you log in. Then it will give you that 500 Internal Server Error. That has been an issue since we first launched Dataverse and I am not sure how to fix it. (It's the core Dataverse code).
