### ISSUE TITLE
question about tickets

### ISSUE THREAD

**Issue by HeatherLeasor** [ADA-ANU/Request-Access-Console#56]
so when a user requests and we reopen the submission  it makes a new ticket. was it supposed to build on the same ticket? Or should we close that origional ticket?

**Comment by mdmADA** [comment]
You can manage it whichever way you want to. Keep the original and link the two tickets together? Or close the first and keep only the most recent one?

**Comment by mdmADA** [comment]
There isn't a way to programatically append to the same ticket.
Issue #60 is supposed to assist by adding the previous ticket # to the new ticket to help physically link the 2 tickets together.
