### ISSUE TITLE
UAT Case 9 - User uses a link for an access request after the request was granted or rejected (so no longer 'live' in the system)

### ISSUE THREAD

**Issue by mdmADA** [ADA-ANU/Request-Access-Console#65]
Steps:

Expected Result:

Actual Result:

**Comment by HeatherLeasor** [comment]
Steps:
1 User requests ANU Poll 2017  file
2 user is awarded or rejected for the specific file in ANU Poll 2017

Expected
No one should be able to open guestbook
should have email to say they were granted/rejected from DV5

Actual Result
Have email from DV5 regarding granting or rejecting 
If click on link in ozticket get a blank circular error


**MJ will make page say redirect to DV to request access or download/check permissions**

**Comment by mdmADA** [comment]
Issue #70 was created for this UAT.

Steps:
1 User requests ANU Poll 2017 file
2 user is awarded or rejected for the specific file in ANU Poll 2017

Expected
should have email to say they were granted/rejected from DV5
user should get a message that the link was for a request that has already been granted or rejected.

MM confirmed this use case now works (1202022) and the Expected Result is the actual result.
