### ISSUE TITLE
UAT Case 10 - User uses form re-open url, doesn't change anything and hits 'Save'

### ISSUE THREAD

**Issue by mdmADA** [ADA-ANU/Request-Access-Console#66]
Steps:

Expected Result:

Actual Result:

**Comment by HeatherLeasor** [comment]
User requests access - SUBMITS
Ticket created
Form re-open link opens the request form
The user doesn't change anything
Clicks Save 

Expected Result:
It saves, sends email if requested by email checkbox

Actual Result:
Get an 'Oops - Invalid Parameter' error  (may have sent the email)

Have to verify that the dataset that is being requested is the dataset that is being emailed save details for.


oops invalid perameter
when hit save after reopen link

**Comment by mdmADA** [comment]
User requests access - SUBMITS
Ticket created
Form re-open link opens the request form
The user doesn't change anything
Clicks Save

Expected Result:
It saves, sends email if requested by email checkbox

MM verified the scenario now works and the Expected Result is what does happen. 03022022

**Comment by mdmADA** [comment]
Issue #73 was opened for this issue. Issue 73 is working (12022022)
