### ISSUE TITLE
the user should have to select at least one restricted file in the request access tool in order to click 'Submit'

### ISSUE THREAD

**Issue by mdmADA** [ADA-ANU/Request-Access-Console#75]
12022022 - currently the use can have no selected restricted files and can click the 'Submit' button.
When the user clicks Submit, the request access application shows 'This form has been submitted' and the dataset is greyed out (with no files selected).
No ticket is created.
No email is sent to user.
The files in Dataverse still show as 'Request Access' after refresh.

Clicking 'Request Access' open the requestaccess tool again and they can select files again.

Change: Disable the 'Submit' button by default, Enable it only if at least one restricted file is selected, Disable it again if the user un-selects all restricted files.

**Comment by MingjingPeng-ANU** [comment]
Issue fixed. Screenshot:
<img width="1379" alt="issue#75" src="https://user-images.githubusercontent.com/60244008/153706201-907a28fb-e44b-4ae1-b517-f0fd9c4e46ce.png">

**Comment by mdmADA** [comment]
Verified working 14022022
