### ISSUE TITLE
In the siblings-dataset page for adding groups of siblings, in the initial drop-down list of dataverses, if a user selects at least one and then de-selects them all, there is an 'Invalid parameter' error.

### ISSUE THREAD

**Issue by mdmADA** [ADA-ANU/Request-Access-Console#79]
Steps.
1. go to the https://dataverse-tools.ada.edu.au/#/dashboard/sibling-datasets and make sure API key is correct
2. Select 1 dataverse in the top dataverse drop down list
3. De-select it
4. Invalid parameter error

**Comment by MingjingPeng-ANU** [comment]
Fixed
